### ISSUE TITLE
its free

### ISSUE THREAD

**Issue by muafakul** [jahirfiquitiva/Frames-Sample#1]
free

**Comment by jahirfiquitiva** [comment]
What? Have you even take the time to set it up properly before you say that? Did you even read the wiki?

**Comment by muafakul** [comment]
please wait

**Comment by muafakul** [comment]
but the notification is always you shall not pass ! ,even if i already insert the licence and api

**Comment by muafakul** [comment]
FIXED , THANKS

**Comment by jahirfiquitiva** [comment]
1. You must have done something wrong yourself. This app is completely free to use, otherwise the whole code would not be public in first instance.
2. Make sure you are using the key Google gives you in developer console. Only that key will work.
3. License check will always be enabled for release builds, so if you want to test the app, just create a debug build.
4. Watch your words before creating an issue. You could have kindly asked why that was happening instead of saying something about me when you didn't even know how to work with the app or how its code works.
5. Just saw that you fixed this. Great. Next time, read the wiki carefully before reporting issues that do not really exist.

**Comment by muafakul** [comment]
i am really sorry ,but how to add admob ads ini that app :'( i really confused and tired how to edit that library

**Comment by jahirfiquitiva** [comment]
I'm sorry but I don't provide default support for any kind of ads. If you want ads in your app, you will have to edit the library source code, and I won't provide any help when doing so.

**Comment by muafakul** [comment]
ok thanks , fixed but you said that

License check will always be enabled for release builds, so if you want to test the app, just create a debug build.

how if i just disable licence check bro ,

**Comment by jahirfiquitiva** [comment]
You can do that, just set the license check to false in the HomeActivity

**Comment by jahirfiquitiva** [comment]
I won't reply here anymore. For further support please join the Google+ community or read the wiki.
https://plus.google.com/communities/117748118619432374563

**Comment by muafakul** [comment]
thanks a lot man
